[package]
name = "curateml"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
colored = "3.0.0"
reqwest = { version = "0.12.15", features = ["blocking"] }
serde-jsonlines = "0.7.0"
serde_json = "1.0.140"
structopt = "0.3.26"
